/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoradebotao;

//import java.util.ArrayList;

public class CalculadoraDeBotao extends javax.swing.JFrame {
    
    
    boolean Adicao = false;
    boolean SubTracao = false;
    boolean Multiplicacao = false;
    boolean Divi = false;
    
    
    
    
    int Num1 = 0;
    
    int Num2 = 0;
    
    public CalculadoraDeBotao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Resultado = new javax.swing.JLabel();
        Nove = new javax.swing.JButton();
        Oito = new javax.swing.JButton();
        Divisao = new javax.swing.JButton();
        Sete = new javax.swing.JButton();
        Seis = new javax.swing.JButton();
        Cinco = new javax.swing.JButton();
        Quatro = new javax.swing.JButton();
        Vezes = new javax.swing.JButton();
        Tres = new javax.swing.JButton();
        Dois = new javax.swing.JButton();
        Um = new javax.swing.JButton();
        Mais = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        Dois1 = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        Menos = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Resultado.setBackground(new java.awt.Color(0, 0, 0));
        Resultado.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        Resultado.setForeground(new java.awt.Color(0, 0, 0));
        Resultado.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Resultado)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Resultado)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Nove.setText("9");
        Nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoveActionPerformed(evt);
            }
        });

        Oito.setText("8");
        Oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OitoActionPerformed(evt);
            }
        });

        Divisao.setText("%");
        Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisaoActionPerformed(evt);
            }
        });

        Sete.setText("7");
        Sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeteActionPerformed(evt);
            }
        });

        Seis.setText("6");
        Seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeisActionPerformed(evt);
            }
        });

        Cinco.setText("5");
        Cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CincoActionPerformed(evt);
            }
        });

        Quatro.setText("4");
        Quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuatroActionPerformed(evt);
            }
        });

        Vezes.setText("X");
        Vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VezesActionPerformed(evt);
            }
        });

        Tres.setText("3");
        Tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TresActionPerformed(evt);
            }
        });

        Dois.setText("2");
        Dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoisActionPerformed(evt);
            }
        });

        Um.setText("1");
        Um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmActionPerformed(evt);
            }
        });

        Mais.setText("+");
        Mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaisActionPerformed(evt);
            }
        });

        Igual.setBackground(new java.awt.Color(153, 255, 204));
        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        Dois1.setText("0");
        Dois1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dois1ActionPerformed(evt);
            }
        });

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        Menos.setText("-");
        Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nove, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Oito, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Um, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dois1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nove, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Oito, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seis, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vezes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mais, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Um, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dois, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dois1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisaoActionPerformed
        Divi = true;
        Num1 = Integer.parseInt(Resultado.getText());
        Resultado.setText("0");
    }//GEN-LAST:event_DivisaoActionPerformed

    private void VezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VezesActionPerformed
        Multiplicacao = true;
        Num1 = Integer.parseInt(Resultado.getText());
        Resultado.setText("0");
    }//GEN-LAST:event_VezesActionPerformed

    private void MaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaisActionPerformed
        Adicao = true;
        Num1 = Integer.parseInt(Resultado.getText());
        Resultado.setText("0");
        
        
    }//GEN-LAST:event_MaisActionPerformed

    private void MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosActionPerformed
        SubTracao = true;
        Num1 = Integer.parseInt(Resultado.getText());
        Resultado.setText("0");
    }//GEN-LAST:event_MenosActionPerformed

    private void UmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmActionPerformed
        int Numeros = 1;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_UmActionPerformed

    private void DoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoisActionPerformed
        int Numeros = 2;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_DoisActionPerformed

    private void TresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TresActionPerformed
       int Numeros = 3;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_TresActionPerformed

    private void QuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuatroActionPerformed
        int Numeros = 4;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_QuatroActionPerformed

    private void CincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CincoActionPerformed
        int Numeros = 5;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_CincoActionPerformed

    private void SeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeisActionPerformed
        int Numeros = 6;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_SeisActionPerformed

    private void SeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeteActionPerformed
        int Numeros = 7;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_SeteActionPerformed

    private void OitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OitoActionPerformed
        int Numeros = 8;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_OitoActionPerformed

    private void Dois1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dois1ActionPerformed
        int Numeros = 0;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_Dois1ActionPerformed

    private void NoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoveActionPerformed
        int Numeros = 9;
        String novoNumeros = String.valueOf(Numeros);
        String numeroAtual = Resultado.getText();
        if(numeroAtual.equals("0")){
            Resultado.setText(novoNumeros);
        }else{
            String novoNumero = numeroAtual + Numeros;
            Resultado.setText(String.valueOf(novoNumero));
        }
        
    }//GEN-LAST:event_NoveActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        if(Adicao == true){
            Num2 = Integer.parseInt(Resultado.getText());
            int SomaFinal = Num1 + Num2;
            Resultado.setText(String.valueOf(SomaFinal));
            Adicao = false;
        }else if(Multiplicacao == true){
            Num2 = Integer.parseInt(Resultado.getText());
            int SomaFinal = Num1 * Num2;
            Resultado.setText(String.valueOf(SomaFinal));
            Multiplicacao = false;
        }else if(SubTracao == true){
            Num2 = Integer.parseInt(Resultado.getText());
            int SomaFinal = Num1 - Num2;
            Resultado.setText(String.valueOf(SomaFinal));
            SubTracao = false;
        }else if(Divi == true){
           Num2 = Integer.parseInt(Resultado.getText());
           int SomaFinal = Num1 / Num2;
           Resultado.setText(String.valueOf(SomaFinal));
           Divi = false; 
        }
    }//GEN-LAST:event_IgualActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        Resultado.setText("0");
    }//GEN-LAST:event_ACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraDeBotao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraDeBotao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton Cinco;
    private javax.swing.JButton Divisao;
    private javax.swing.JButton Dois;
    private javax.swing.JButton Dois1;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Mais;
    private javax.swing.JButton Menos;
    private javax.swing.JButton Nove;
    private javax.swing.JButton Oito;
    private javax.swing.JButton Quatro;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Seis;
    private javax.swing.JButton Sete;
    private javax.swing.JButton Tres;
    private javax.swing.JButton Um;
    private javax.swing.JButton Vezes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
